# Generated by Django 6.0.4 on 2026-05-02 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('p', models.FloatField()),
                ('f', models.FloatField()),
                ('steps_executed', models.IntegerField(default=0)),
                ('grid_data', models.BinaryField()),
                ('fire_histogram', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
